services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    networks:
      - internal

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
      - minio
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: https://admin.lemnartdecor.md
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      FRONTEND_STORE_URL: https://store.lemnartdecor.md
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_USE_SSL: "false"
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: uploads
      MINIO_PUBLIC_URL: https://minio.lemnartdecor.md
    networks:
      - internal
    ports:
      - "127.0.0.1:3001:3001"

  store:
    build:
      context: ./store
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://admin.lemnartdecor.md/api/ac0031e6-7cc4-4095-b711-c98a52cfcaa6
        NEXT_PUBLIC_MINIO_HOSTNAME: minio.lemnartdecor.md
        NEXT_PUBLIC_SITE_URL: https://store.lemnartdecor.md
        MINIO_USE_SSL: "true"
    restart: unless-stopped
    depends_on:
      - admin
    environment:
      NEXT_PUBLIC_API_URL: https://admin.lemnartdecor.md/api/ac0031e6-7cc4-4095-b711-c98a52cfcaa6
      MINIO_USE_SSL: "true"
      NEXT_PUBLIC_SITE_URL: https://store.lemnartdecor.md
    networks:
      - internal
    ports:
      - "127.0.0.1:3002:3002"

volumes:
  postgres_data:
  minio_data:

networks:
  internal:
